### ISSUE TITLE
Game-List Feature Parity Checklist

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#180]
This Github issue is just a checklist to get an overview of the features present in GL that Atlas yet has.

- [ ] F95 "Browsing", having metadata and images for titles you have not installed. Pretty much have all the metadata for all the files locally cached in the client for easy use and access.
- [ ] Update filter/notifications. (If latest scraped version value is different than any of the installed versions then count it as out of sync and not the latest!)
- [ ] Tag Searching
- [ ] Exclusion Searching -title -creator -tag and so on to exclude said things from search.
- [ ] Right click Thumbnail to install version to said title.
- [ ] Delete last installed version as an optional tick when installing a new version.
- [ ] Play states, set latest version as "played" or "finished" or manually set one of the selected versions as such.
This expands a bit more than what GL does by doing it per version. Keeping it per version means when you install a new version, the title is no longer "finished" without needing to un-flag it. Unsure if this should be saved in the version part of the db though!
- [ ] Tag list on detail page.
- [ ] Screenshots on detail page.
- [ ] Version list with easy delete buttons on detail page.
- [ ] Larger Image Viewer (GL does Full Screen but thats overkill, maybe expand on hover or click?)
- [ ] Table/List View
- [ ] Extract Archive on install (individual)
- [ ] Archive Game (zip them up, unsure how many uses this one)
- [ ] Scrape F95 Metadata locally without a metadata server.
- [ ] Refresh/scrape metadata locally on a per title basis (detailed page)
- [ ] Add and download metadata based on F95 thread URL.
- [ ] Move installed title to a new location. ![image](https://github.com/KJNeko/Atlas/assets/8496821/9b23b964-d420-4816-8bb5-4ea2bf96cd25)
- [ ] Tag Ratings, (tags can have a rating of 0-10 to indicate how "important" or how in focus it is for that title, for example you could have a tag like "Impressive Graphics" and when its really impressive its a 10 and if its not really that impressive its closer to 0. ![image](https://github.com/KJNeko/Atlas/assets/8496821/8c547212-e090-4924-83f3-cb7795be51a5)
- [ ] Expansive Metadata and interactions on right click, should probably be a hover. ![image](https://github.com/KJNeko/Atlas/assets/8496821/01720c25-6d16-431c-b6e3-40157eeef7bf)
- [ ] Updates Window that lists all the new updates since last Sync, Updates has an Update Overlay and New releases got a New overlay. This window got an easy feature to select all, check off multiple or check off installed or favourite titles only with a single click to open all threads in your default browser. If this is added then feeding it to the MyJdownloader api makes more sense! ![image](https://github.com/KJNeko/Atlas/assets/8496821/887b4164-2908-4ee8-beef-bdc428db2b6b)
